### ISSUE TITLE
Object-Iterate-1.148: The table of contents appears to have only 'NAME' on MetaCPAN

### ISSUE THREAD

**Issue by twata1** [briandfoy/object-iterate#17]
Hello,

To me, apparently the table of contents looks different from the old version.

Please see:
https://metacpan.org/pod/Object::Iterate
https://metacpan.org/release/BRIANDFOY/Object-Iterate-1.148/view/lib/Object/Iterate.pm

https://metacpan.org/release/BDFOY/Object-Iterate-1.144/view/preprocess/Object/Iterate.pm.PL

Thank you,

**Comment by briandfoy** [comment]
This happened because the Pod was previously only in the *preprocess/Object/Iterate.pm.PL*, which creates the real *lib/Object/Iterate.pm* to install. However, MetaCPAN doesn't care about all that. I added *lib/Object/Iterate.pod*, which just the docs, so it's always there. This seems to give MetaCPAN something to find in 1.149.

Thanks,
